name: deploy
on:
  push:
    paths:
      - 'src/**'
      - 'static/**'
      - '.github/workflows/**'
      - 'package.json'
      - 'yarn.lock'
      - 'Dockerfile'
      - 'cloudbuild.yaml'
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Create dot env file
        run: |
          touch .env.production
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env.production
          echo "PUBLIC_TWITTER_ID=${{ secrets.PUBLIC_TWITTER_ID }}" >> .env.production
          echo "SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}" >> .env.production
          echo "SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}" >> .env.production

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Build and deploy'
        run: 'gcloud builds submit . --substitutions _LOCATION=${{ secrets.GCP_REGION }},_REPOSITORY=${{ secrets.GCP_CLOUD_RUN_SERVICE_NAME }},_IMAGE=${{ secrets.GCP_IMAGE }},_SERVICE_NAME=${{ secrets.GCP_CLOUD_RUN_SERVICE_NAME }}'
